# Generated by Django 4.1.1 on 2022-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverCliNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('driverType', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('homePhone', models.CharField(max_length=100)),
                ('cellPhone', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('RegistrationExpires', models.DateField()),
                ('terminated', models.BooleanField()),
                ('terminatedDate', models.DateField()),
                ('licenseNumber', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
