# Generated by Django 4.1.1 on 2022-11-07 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default='2022-01-01')),
                ('contractorBusinessName', models.CharField(default='TotallyRealContractor', max_length=100)),
                ('firstName', models.CharField(default='Bob', max_length=100)),
                ('lastName', models.CharField(default='Builder', max_length=100)),
                ('addressNumber', models.CharField(default='123', max_length=100)),
                ('addressLocation', models.CharField(default='Street', max_length=100)),
                ('city', models.CharField(default='Real City', max_length=100)),
                ('state', models.CharField(default='CA', max_length=100)),
                ('zip', models.CharField(default='12345', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='contractorBusiness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drivers.contractor'),
        ),
    ]
