# Generated by Django 4.1.1 on 2022-11-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_contractor_driver_contractorbusiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contractorBusiness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.contractor'),
        ),
    ]
