# Generated by Django 4.1.1 on 2022-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_contractorbusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
        migrations.AlterField(
            model_name='driver',
            name='terminatedDate',
            field=models.DateField(null=True),
        ),
    ]
