# Generated by Django 4.1.1 on 2022-11-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driver_image_alter_driver_terminateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='terminatedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
