# Generated by Django 4.1.1 on 2022-11-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driver_terminateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cellPhone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='driver',
            name='homePhone',
            field=models.CharField(max_length=13),
        ),
    ]
