# Generated by Django 4.1.1 on 2022-11-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressNumber', models.CharField(default='123', max_length=100)),
                ('addressLocation', models.CharField(default='Street', max_length=100)),
                ('city', models.CharField(default='Real City', max_length=100)),
                ('state', models.CharField(default='CA', max_length=100)),
                ('zip', models.CharField(default='12345', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default='2022-01-01')),
                ('contractorBusinessName', models.CharField(default='TotallyRealContractor', max_length=100)),
                ('firstName', models.CharField(default='Bob', max_length=100)),
                ('lastName', models.CharField(default='Builder', max_length=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.address')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverCliNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('driverType', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('homePhone', models.CharField(max_length=13)),
                ('cellPhone', models.CharField(max_length=13)),
                ('startDate', models.DateField()),
                ('dateOfBirth', models.DateField()),
                ('RegistrationExpires', models.DateField()),
                ('terminated', models.BooleanField()),
                ('terminatedDate', models.DateField(blank=True, null=True)),
                ('licenseNumber', models.CharField(max_length=100)),
                ('licenseClass', models.CharField(max_length=13)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.address')),
                ('contractorBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=100)),
                ('vehicleYear', models.IntegerField()),
                ('vehicleMake', models.CharField(max_length=100)),
                ('vinNumber', models.CharField(max_length=100)),
                ('licensePlate', models.CharField(max_length=100)),
                ('combinedVehicleWeight', models.IntegerField()),
                ('registrationExires', models.DateField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.driver')),
            ],
        ),
    ]
