# Generated by Django 4.1.1 on 2022-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='emergencyContactFirstName',
            field=models.CharField(default='FirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergencyContactLastName',
            field=models.CharField(default='LastName', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergencyPhone',
            field=models.CharField(default='310-987-1327', max_length=13),
        ),
    ]
