# Generated by Django 4.1.1 on 2022-11-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_driver_emergencycontactfirstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contractors.vehicle'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contractors.address'),
        ),
    ]
